version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./app/src:/home/app/app/src
      - tmp-public:/home/app/public
    command: npm run watch
  server:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    restart: always
    volumes:
      - ./server:/home/app/server
      - tmp-public:/home/app/public
    command: npm start
    environment:
      - NODE_ENV=localhost
    ports:
      - "127.0.0.1:8080:8083"
volumes:
  tmp-public: